"""Synthetic league data for demos and tests.

EVERYTHING THIS MODULE PRODUCES IS MADE UP. It exists so the pipeline can be
exercised — and its maths verified — without a network connection, and so
`vb demo` shows a populated dashboard on a fresh clone. Real club names are
used purely as labels; the results, statistics and prices are drawn from a
random model and mean nothing.

Because the generator knows the true probabilities it sampled from, the tests
can check that the value engine finds the edges that were deliberately planted
and ignores the prices that are fair.
"""

from __future__ import annotations

import math
import random
import sqlite3
from datetime import datetime, timedelta

from .repo import upsert_match, upsert_odds

SYNTHETIC_TAG = "SYNTHETIC — generated by vb.sample, not real data"

TEAMS = {
    # Lists are ordered strongest-first: the generator builds a ladder from the
    # ordering, which keeps the fake tables looking plausible.
    "E0": ["Manchester City", "Arsenal", "Liverpool", "Chelsea",
           "Tottenham Hotspur", "Aston Villa", "Newcastle United",
           "Manchester United", "Brighton and Hove Albion", "West Ham United",
           "Nottingham Forest", "Brentford", "Fulham", "Crystal Palace",
           "AFC Bournemouth", "Everton", "Wolverhampton Wanderers",
           "Leicester City", "Ipswich Town", "Southampton"],
    "E1": ["Leeds United", "Burnley", "Sheffield United", "Sunderland",
           "Middlesbrough", "West Bromwich Albion", "Coventry City", "Norwich City",
           "Watford", "Millwall", "Blackburn Rovers", "Bristol City",
           "Swansea City", "Sheffield Wednesday", "Preston North End", "Stoke City",
           "Cardiff City", "Queens Park Rangers", "Hull City", "Derby County",
           "Portsmouth", "Oxford United", "Plymouth Argyle", "Luton Town"],
    "E2": ["Birmingham City", "Wrexham", "Bolton Wanderers", "Huddersfield Town",
           "Barnsley", "Charlton Athletic", "Blackpool", "Wigan Athletic",
           "Reading", "Peterborough United", "Stockport County", "Rotherham United",
           "Lincoln City", "Bristol Rovers", "Northampton Town", "Mansfield Town",
           "Exeter City", "Wycombe Wanderers", "Leyton Orient", "Shrewsbury Town",
           "Burton Albion", "Cambridge United", "Crawley Town", "Stevenage"],
    "E3": ["Port Vale", "Walsall", "Bradford City", "Notts County", "Chesterfield",
           "Milton Keynes Dons", "Doncaster Rovers", "Gillingham", "Colchester United",
           "Swindon Town", "Crewe Alexandra", "Fleetwood Town", "Grimsby Town",
           "Harrogate Town", "Salford City", "Bromley", "Newport County",
           "Accrington Stanley", "Barrow", "Carlisle United", "Cheltenham Town",
           "Morecambe", "Tranmere Rovers", "AFC Wimbledon"],
    "EC": ["York City", "Forest Green Rovers", "Oldham Athletic", "Southend United",
           "Halifax Town", "Gateshead", "Altrincham", "Rochdale", "Woking",
           "Sutton United", "Eastleigh", "Solihull Moors", "Boreham Wood",
           "Hartlepool United", "Yeovil Town", "Tamworth", "Braintree Town",
           "Wealdstone", "Ebbsfleet United", "Dagenham and Redbridge",
           "Aldershot Town", "Maidenhead United", "Scunthorpe United", "Truro City"],
    "SC0": ["Celtic", "Rangers", "Heart of Midlothian", "Hibernian", "Aberdeen",
            "Dundee United", "St Mirren", "Motherwell", "Kilmarnock",
            "Ross County", "Dundee", "St Johnstone"],
    "SC1": ["Falkirk", "Partick Thistle", "Raith Rovers", "Ayr United",
            "Dunfermline Athletic", "Greenock Morton", "Airdrieonians",
            "Queen's Park", "Hamilton Academical", "Livingston"],
    "SC2": ["Cove Rangers", "Alloa Athletic", "Arbroath", "Montrose",
            "Kelty Hearts", "Stenhousemuir", "Annan Athletic", "Queen of the South",
            "Inverness Caledonian Thistle", "Dumbarton"],
    "SC3": ["Peterhead", "East Fife", "Elgin City", "Forfar Athletic",
            "Stirling Albion", "Stranraer", "Clyde", "Edinburgh City",
            "Bonnyrigg Rose", "The Spartans"],
    "D1": ["Bayern Munich", "Borussia Dortmund", "Bayer Leverkusen", "RB Leipzig",
           "Eintracht Frankfurt", "VfB Stuttgart", "SC Freiburg", "Union Berlin",
           "Werder Bremen", "Borussia Monchengladbach", "VfL Wolfsburg", "Mainz 05",
           "FC Augsburg", "Hoffenheim", "VfL Bochum", "FC Heidenheim",
           "St Pauli", "Holstein Kiel"],
    "I1": ["Inter Milan", "AC Milan", "Juventus", "Napoli", "AS Roma", "Lazio",
           "Atalanta", "Fiorentina", "Bologna", "Torino", "Udinese", "Genoa",
           "Cagliari", "Hellas Verona", "Lecce", "Empoli", "Monza", "Parma",
           "Como", "Venezia"],
    "SP1": ["Real Madrid", "Barcelona", "Atletico Madrid", "Athletic Bilbao",
            "Real Sociedad", "Real Betis", "Villarreal", "Sevilla", "Valencia",
            "Girona", "Celta Vigo", "Osasuna", "Mallorca", "Getafe",
            "Deportivo Alaves", "Espanyol", "Rayo Vallecano", "Las Palmas",
            "Leganes", "Real Valladolid"],
}

# Rough league scoring character, used to keep the fake data plausible.
LEAGUE_PROFILE = {
    "E0": dict(goals=2.80, corners=10.3, cards=4.0, home=0.24),
    "E1": dict(goals=2.55, corners=10.8, cards=4.4, home=0.26),
    "E2": dict(goals=2.60, corners=10.5, cards=4.2, home=0.27),
    "E3": dict(goals=2.55, corners=10.0, cards=4.0, home=0.28),
    "EC": dict(goals=2.65, corners=10.2, cards=4.3, home=0.29),
    "SC0": dict(goals=2.70, corners=10.0, cards=4.1, home=0.25),
    "SC1": dict(goals=2.75, corners=9.8, cards=4.0, home=0.27),
    "SC2": dict(goals=2.80, corners=9.5, cards=3.9, home=0.28),
    "SC3": dict(goals=2.85, corners=9.3, cards=3.8, home=0.28),
    "D1": dict(goals=3.10, corners=10.1, cards=3.6, home=0.23),
    "I1": dict(goals=2.70, corners=10.4, cards=4.8, home=0.22),
    "SP1": dict(goals=2.55, corners=9.8, cards=5.2, home=0.24),
}


def _strengths(rng: random.Random, teams: list[str]) -> dict[str, tuple[float, float]]:
    """Latent attack/defence strengths, spread wider in stronger leagues."""
    out = {}
    for i, team in enumerate(teams):
        # a gentle ladder plus noise, so the table has a shape
        rank = 1 - (i / max(1, len(teams) - 1))
        out[team] = (
            rng.gauss(0.28 * (rank - 0.5), 0.13),      # attack: higher scores more
            rng.gauss(0.28 * (rank - 0.5), 0.13),      # defence: higher concedes less
        )
    return out


def _poisson(rng: random.Random, lam: float) -> int:
    lam = max(0.02, lam)
    if lam > 30:
        return max(0, int(rng.gauss(lam, math.sqrt(lam))))
    target, total, k = math.exp(-lam), 1.0, 0
    while True:
        total *= rng.random()
        if total <= target:
            return k
        k += 1
        if k > 40:
            return k


def round_robin(teams: list[str]) -> list[tuple[str, str, int]]:
    """Full double round robin, returned as (home, away, matchday)."""
    squad = list(teams)
    if len(squad) % 2:
        squad.append(None)
    n = len(squad)
    rounds = []
    for day in range(n - 1):
        pairs = []
        for i in range(n // 2):
            a, b = squad[i], squad[n - 1 - i]
            if a and b:
                pairs.append((a, b) if day % 2 == 0 else (b, a))
        rounds.append(pairs)
        squad = [squad[0]] + [squad[-1]] + squad[1:-1]
    fixtures = []
    for day, pairs in enumerate(rounds):
        for home, away in pairs:
            fixtures.append((home, away, day))
    for day, pairs in enumerate(rounds):
        for home, away in pairs:
            fixtures.append((away, home, day + len(rounds)))
    return fixtures


def _prices(true_probs: dict[str, float], rng: random.Random, margin: float,
            books: list[str]) -> dict[str, dict[str, float]]:
    """Turn true probabilities into quoted prices, book by book.

    Each book gets its own small opinion error, so the best available price
    sometimes sits above fair value — which is exactly the situation the value
    engine is supposed to detect.
    """
    quotes: dict[str, dict[str, float]] = {}
    for book in books:
        noise = 0.012 if book.endswith("_close") else 0.035
        skew = {k: math.exp(rng.gauss(0, noise)) for k in true_probs}
        raw = {k: max(1e-4, p * skew[k]) for k, p in true_probs.items()}
        total = sum(raw.values())
        book_margin = margin * rng.uniform(0.85, 1.15)
        quotes[book] = {
            k: round(max(1.01, 1.0 / (v / total * (1 + book_margin))), 2)
            for k, v in raw.items()
        }
    return quotes


BOOKS = ["bet365", "skybet", "paddypower", "williamhill", "ladbrokes_uk",
         "coral", "betfred", "betvictor"]


def generate_league(
    conn: sqlite3.Connection,
    league_code: str,
    season: str,
    start_date: datetime,
    played_fraction: float = 0.6,
    seed: int = 0,
    upcoming_days: int = 8,
    with_history_odds: bool = True,
) -> dict[str, int]:
    """Create one synthetic season: played matches with stats, then fixtures with prices."""
    rng = random.Random(hash((league_code, season, seed)) & 0xFFFFFFFF)
    teams = TEAMS[league_code]
    profile = LEAGUE_PROFILE[league_code]
    strength = _strengths(rng, teams)
    fixtures = round_robin(teams)
    matchdays = max(d for _, _, d in fixtures) + 1
    cutoff = int(matchdays * played_fraction)

    base = math.log(profile["goals"] / 2)
    played = scheduled = priced = 0

    for home, away, day in fixtures:
        kickoff = (start_date + timedelta(days=7 * day)).replace(
            hour=15, minute=0, second=0, microsecond=0)
        ha, hd = strength[home]
        aa, ad = strength[away]
        lam_home = math.exp(base + ha - ad + profile["home"])
        lam_away = math.exp(base + aa - hd)

        if day < cutoff:
            hg, ag = _poisson(rng, lam_home), _poisson(rng, lam_away)
            # shots and corners scale with attacking output plus noise
            hs = max(hg, _poisson(rng, 5 + 4.2 * lam_home))
            aws = max(ag, _poisson(rng, 5 + 4.2 * lam_away))
            hst = max(hg, min(hs, _poisson(rng, 0.34 * hs)))
            ast = max(ag, min(aws, _poisson(rng, 0.34 * aws)))
            corners_total = profile["corners"] * rng.uniform(0.6, 1.5)
            share = lam_home / (lam_home + lam_away)
            hc = _poisson(rng, corners_total * share)
            ac = _poisson(rng, corners_total * (1 - share))
            cards_total = profile["cards"] * rng.uniform(0.5, 1.6)
            hy = _poisson(rng, cards_total * 0.47)
            ay = _poisson(rng, cards_total * 0.53)
            hr = 1 if rng.random() < 0.035 else 0
            ar = 1 if rng.random() < 0.045 else 0
            match_id = upsert_match(
                conn, league_code, season, kickoff.isoformat(timespec="seconds"),
                home, away, status="played", source="sample",
                fthg=hg, ftag=ag, hs=hs, **{"as": aws}, hst=hst, ast=ast,
                hc=hc, ac=ac, hf=_poisson(rng, 11), af=_poisson(rng, 11),
                hy=hy, ay=ay, hr=hr, ar=ar,
                home_xg=round(max(0.05, rng.gauss(lam_home, 0.35)), 2),
                away_xg=round(max(0.05, rng.gauss(lam_away, 0.35)), 2),
                referee=f"Ref {(day % 12) + 1}",
            )
            played += 1
            if with_history_odds:
                priced += _write_prices(conn, match_id, lam_home, lam_away, rng,
                                        kickoff, closing=True)
            continue

        # Upcoming: only the next block of fixtures gets priced up.
        if kickoff > start_date + timedelta(days=7 * cutoff + upcoming_days):
            continue
        match_id = upsert_match(
            conn, league_code, season, kickoff.isoformat(timespec="seconds"),
            home, away, status="scheduled", source="sample",
        )
        scheduled += 1

        priced += _write_prices(conn, match_id, lam_home, lam_away, rng, kickoff)

    return {"played": played, "scheduled": scheduled, "prices": priced}


def true_probabilities(lam_home: float, lam_away: float) -> dict[str, dict]:
    """The probabilities the fake fixture was actually generated from."""
    ph = pd = pa = 0.0
    for hg in range(9):
        for ag in range(9):
            p = _pmf(lam_home, hg) * _pmf(lam_away, ag)
            if hg > ag:
                ph += p
            elif hg == ag:
                pd += p
            else:
                pa += p
    total = ph + pd + pa
    ph, pd, pa = ph / total, pd / total, pa / total
    p_over = sum(_pmf(lam_home, hg) * _pmf(lam_away, ag)
                 for hg in range(9) for ag in range(9) if hg + ag > 2.5)
    p_btts = (1 - _pmf(lam_home, 0)) * (1 - _pmf(lam_away, 0))
    return {
        "h2h": ({"home": ph, "draw": pd, "away": pa}, None),
        "totals": ({"over": p_over, "under": 1 - p_over}, 2.5),
        "btts": ({"yes": p_btts, "no": 1 - p_btts}, None),
    }


def _write_prices(conn: sqlite3.Connection, match_id: int, lam_home: float,
                  lam_away: float, rng: random.Random, kickoff, closing: bool = False
                  ) -> int:
    """Quote every book up for one fixture; optionally add a sharper closing line."""
    taken = kickoff.date().isoformat()
    written = 0
    for market, (probs, line) in true_probabilities(lam_home, lam_away).items():
        margin = 0.045 if market == "h2h" else 0.055
        for book, quote in _prices(probs, rng, margin, BOOKS).items():
            for selection, price in quote.items():
                upsert_odds(conn, match_id, book, market, selection, price, line,
                            taken_at=taken)
                written += 1
        if closing:
            # The closing line is tighter and closer to the truth, which is what
            # makes closing line value a meaningful measure.
            for book, quote in _prices(probs, rng, 0.025, ["market_close"]).items():
                for selection, price in quote.items():
                    upsert_odds(conn, match_id, book, market, selection, price,
                                line, taken_at=taken, is_closing=True)
                    written += 1
    return written


def generate_outrights(conn: sqlite3.Connection, league_code: str, season: str,
                       seed: int = 0) -> int:
    """Fake outright prices for the season-long markets, so the demo has some."""
    from .models.ratings import fit_league
    from .models.season import simulate_season

    model = fit_league(conn, league_code)
    if model is None:
        return 0
    outlook = simulate_season(conn, model, season, simulations=3000, seed=seed)
    if outlook is None:
        return 0
    rng = random.Random(seed + 991)
    written = 0
    markets = [("winner", lambda tid: outlook.title(tid)),
               ("top_four", lambda tid: outlook.probability_position(tid, 4)),
               ("relegation", lambda tid: outlook.probability_bottom(tid, 3))]
    for market, prob_fn in markets:
        for team_id, name in outlook.teams.items():
            prob = prob_fn(team_id)
            if prob < 0.02 or prob > 0.80:
                continue
            for book in rng.sample(BOOKS, 3):
                # a fat outright margin plus each book's own opinion
                quoted = prob * math.exp(rng.gauss(0, 0.10)) * 1.18
                price = round(max(1.05, 1 / min(0.97, quoted)), 2)
                conn.execute(
                    "INSERT INTO outright_odds (league_code, season, market, "
                    "selection, bookmaker, price, taken_at) VALUES (?,?,?,?,?,?,?) "
                    "ON CONFLICT(league_code, season, market, selection, bookmaker, "
                    "taken_at) DO UPDATE SET price = excluded.price",
                    (league_code, season, market, name, book, price,
                     datetime.now().date().isoformat()),
                )
                written += 1
    return written


def _pmf(lam: float, k: int) -> float:
    return math.exp(-lam) * lam ** k / math.factorial(k)


def generate_all(conn: sqlite3.Connection, season: str = "2025/26",
                 leagues: list[str] | None = None, seed: int = 7,
                 played_fraction: float = 0.6) -> dict[str, dict[str, int]]:
    """Populate every configured domestic league with a synthetic season."""
    codes = leagues or list(TEAMS)
    today = datetime.now()
    out = {}
    for code in codes:
        if code not in TEAMS:
            continue
        # Work backwards so the "current" matchday lands on today.
        teams = len(TEAMS[code])
        total_days = (teams - 1) * 2
        cutoff = int(total_days * played_fraction)
        start = today - timedelta(days=7 * cutoff)
        out[code] = generate_league(conn, code, season, start, played_fraction,
                                    seed, upcoming_days=8)
    for code in ("E0", "E1", "SC0"):
        if code in out:
            out[code]["outrights"] = generate_outrights(conn, code, season, seed)
    return out
